import NavBar from "@/components/NavBar";
import "./globals.css";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#D3F1E8]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
